server:
  port: 8888

# cloud配置中心仓库
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/GeniusOrIdiot/spring-cloud-config.git
          search-paths: repos

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
